---
services:
  waha:
    image: devlikeapro/waha
    container_name: "waha-dev"
    env_file:
      - .env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: unless-stopped
